### PR TITLE
Handle multiline go vet messages.

### PR DESCRIPTION
**Pull request by chilic**
This PR is fix for:
https://github.com/SublimeLinter/SublimeLinter-govet/pull/12#issuecomment-436534526
https://github.com/SublimeLinter/SublimeLinter-govet/pull/12#issuecomment-436709731
https://github.com/SublimeLinter/SublimeLinter-govet/pull/11#issuecomment-431462474
https://github.com/SublimeLinter/SublimeLinter-govet/pull/11#issuecomment-431697979

Related issues:
https://github.com/SublimeLinter/SublimeLinter-govet/issues/10

### CODE REVIEW

**Comment by chilic** [comment]
Hello @MeruFM @kaste 
Could you pleas review this PR. Thanks.

**Comment by chilic** [comment]
@kaste Thank you for this comments. And yes, it's works))

**Comment by chilic** [comment]
Hello, @kaste @MeruFM do you have any objections or concerns? Thank you.

**Comment by MeruFM** [comment]
Hi @chilic 
What version of go and sublime text are you using?
I'm unable to get any lint warnings to show up using your code changes.

I'm on SublimeLinter v4.9.4
SublimeText 3.1.1

The old code also seems buggy when not run under a project so this is a good line change
https://github.com/SublimeLinter/SublimeLinter-govet/pull/14/files#diff-6c1f4f1574c85da37dc4dd59341c9a39R6

**Comment by kaste** [comment]
Using `$file_path` has been discussed. Other go linters also do this right now. Linting single/orphaned files has been considered an edge case (where you can also just turn linting off), instead linting whole packages (=folders) is the way to go here. (Reminder: I don't use go, I just help with the code review, and remember some discussions here and in other repos.)

**Comment by MeruFM** [comment]
@kaste Thanks for the context.

In that case, this looks good. Seems to work correctly.

**Comment by chilic** [comment]
Hi @MeruFM,
I guess @kaste provide all information. 
If you guys want I can go ahead and start working on linter for single file in separate pull request.

Thank you.

**Comment by MeruFM** [comment]
@chilic You can, but that behavior is already conforming to the standards of other linters.

**Pull request merged**
