### PR TITLE
handle missing imports

### PR DESCRIPTION
**Pull request by chilic**
Improve command to run vet tool: `go vet file_path/file_name.go`

https://github.com/SublimeLinter/SublimeLinter-govet/issues/10

### CODE REVIEW

**Comment by kaste** [comment]
Hi @MeruFM, you just merged without leaving any comments. I have still some concerns:

1. `col` was actually optional before, now it isn't anymore
2. In `${file_path:file_name}`, I doubt that `file_name` is what we want here, but it is also redundant bc if we don't have a _file_path_ we also don't have a _file_name_. 
3. This will probably report errors from multiple files in one go, and if so the results must be filtered. See https://github.com/SublimeLinter/SublimeLinter-govet/pull/11#issuecomment-431462474

**Comment by chilic** [comment]
@kaste @MeruFM can we have chat? I really want to finish this PR. Thanks.

**Comment by MeruFM** [comment]
@chilic you can make another PR and we can talk in there.

Col should be optional, unless go vet behavior changed
`((?P<col>\d+):)?`

**Comment by kaste** [comment]
@chilic Just ask anything you want here. Sure, we get this done. 👍 

Please address my concerns from the comment above https://github.com/SublimeLinter/SublimeLinter-govet/pull/12#issuecomment-436534526 

Note that I'm not a go user, I just do the code review.

**Pull request merged**
